#!/usr/bin/env node

import fs from "node:fs";
import path from "node:path";
import readline from "node:readline/promises";
import { stdin as input, stdout as output } from "node:process";

const envPath = path.resolve(process.cwd(), ".env");

function parseEnvLines(lines) {
  const map = new Map();
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq < 0) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if ((value.startsWith("\"") && value.endsWith("\"")) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    map.set(key, value);
  }
  return map;
}

function isTemplateUrl(url) {
  if (!url) return true;
  return /project-ref|<project-ref>|password@/i.test(url);
}

function isValidPostgresUrl(url) {
  if (!url) return false;
  try {
    const parsed = new URL(url);
    if (!["postgres:", "postgresql:"].includes(parsed.protocol)) return false;
    if (!parsed.hostname || /[<>]/.test(parsed.hostname)) return false;
    if (!parsed.pathname || parsed.pathname === "/") return false;
    return true;
  } catch {
    return false;
  }
}

function isSqliteUrl(url) {
  return typeof url === "string" && url.startsWith("file:");
}

function readEnvFile() {
  if (!fs.existsSync(envPath)) {
    return [];
  }
  return fs.readFileSync(envPath, "utf8").split(/\r?\n/);
}

function upsertLine(lines, key, value) {
  const escaped = value.replace(/\\/g, "\\\\").replace(/"/g, "\\\"");
  const nextLine = `${key}="${escaped}"`;
  const idx = lines.findIndex((line) => line.trim().startsWith(`${key}=`));
  if (idx >= 0) {
    lines[idx] = nextLine;
  } else {
    lines.push(nextLine);
  }
}

function checkConfig() {
  const lines = readEnvFile();
  const env = parseEnvLines(lines);
  const databaseUrl = env.get("DATABASE_URL") ?? "";
  const directUrl = env.get("DIRECT_URL") ?? "";

  const reasons = [];
  const sqliteMode = isSqliteUrl(databaseUrl) || isSqliteUrl(directUrl);

  if (sqliteMode) {
    reasons.push("SQLite URL detected. PostgreSQL is required in v2.");
  }
  if (isTemplateUrl(databaseUrl)) reasons.push("DATABASE_URL is still template.");
  if (isTemplateUrl(directUrl)) reasons.push("DIRECT_URL is still template.");
  if (!isValidPostgresUrl(databaseUrl)) reasons.push("DATABASE_URL is not a valid postgres URL.");
  if (!isValidPostgresUrl(directUrl)) reasons.push("DIRECT_URL is not a valid postgres URL.");

  return {
    ok: reasons.length === 0,
    reasons,
    databaseUrl,
    directUrl,
    sqliteMode,
  };
}

function setLocalPostgresEnv() {
  const lines = readEnvFile();
  if (lines.length === 0) {
    lines.push("# Local PostgreSQL (default user/password postgres — matches .env.example)");
  }

  const localPostgresUrl = "postgresql://postgres:postgres@localhost:5432/projectmanagepro";
  upsertLine(lines, "DATABASE_URL", localPostgresUrl);
  upsertLine(lines, "DIRECT_URL", localPostgresUrl);
  fs.writeFileSync(envPath, `${lines.join("\n").replace(/\n{3,}/g, "\n\n")}\n`, "utf8");
}

/** Docker Compose postgres (see docker-compose.yml) — host port 5433 */
function setDockerPostgresEnv() {
  const lines = readEnvFile();
  if (lines.length === 0) {
    lines.push("# Docker PostgreSQL (npm run db:docker:up)");
  }

  const url = "postgresql://postgres:postgres@localhost:5433/projectmanagepro";
  upsertLine(lines, "DATABASE_URL", url);
  upsertLine(lines, "DIRECT_URL", url);
  fs.writeFileSync(envPath, `${lines.join("\n").replace(/\n{3,}/g, "\n\n")}\n`, "utf8");
}

function setServerPostgresEnv(password) {
  const encoded = encodeURIComponent(password);
  const url = `postgresql://postgres:${encoded}@localhost:5432/projectmanagepro`;
  const body = `# Server PostgreSQL (generated by 1_Setup)\nDATABASE_URL="${url}"\nDIRECT_URL="${url}"\n`;
  fs.writeFileSync(envPath, body, "utf8");
}

async function runInteractiveWizard() {
  const rl = readline.createInterface({ input, output });
  try {
    console.log("");
    console.log("=== Database URL Setup Wizard ===");
    console.log("v2 requires PostgreSQL. Set local Postgres or Supabase URLs.");
    console.log("");

    const mode = (
      await rl.question(
        "Choose mode [1: local postgres (recommended), 2: paste full URLs, 3: project-ref + password] (default 1): ",
      )
    ).trim() || "1";

    let databaseUrl = "";
    let directUrl = "";

    if (mode === "1") {
      databaseUrl = "postgresql://postgres:postgres@localhost:5432/projectmanagepro";
      directUrl = databaseUrl;
    } else if (mode === "3") {
      const projectRef = (await rl.question("Supabase project-ref (example: abcdxyz123): ")).trim();
      const rawPassword = await rl.question("Supabase DB password: ");
      const encodedPassword = encodeURIComponent(rawPassword.trim());

      if (!projectRef || !encodedPassword) {
        throw new Error("project-ref and password are required.");
      }

      databaseUrl = `postgresql://postgres:${encodedPassword}@db.${projectRef}.supabase.co:5432/postgres`;
      directUrl = databaseUrl;
    } else {
      databaseUrl = (await rl.question("Paste DATABASE_URL: ")).trim();
      directUrl = (await rl.question("Paste DIRECT_URL (Enter to reuse DATABASE_URL): ")).trim();
      if (!directUrl) directUrl = databaseUrl;
    }

    const lines = readEnvFile();
    if (lines.length === 0) {
      lines.push(mode === "1" ? "# Local PostgreSQL" : "# Supabase / PostgreSQL");
    }

    upsertLine(lines, "DATABASE_URL", databaseUrl);
    upsertLine(lines, "DIRECT_URL", directUrl);

    fs.writeFileSync(envPath, `${lines.join("\n").replace(/\n{3,}/g, "\n\n")}\n`, "utf8");
    console.log("");
    console.log(`[DONE] Updated ${envPath}`);
  } finally {
    rl.close();
  }
}

function printCheckResult(result) {
  if (result.ok) {
    console.log("[OK] DATABASE_URL and DIRECT_URL look valid.");
    return;
  }

  console.log("[INVALID] DB URL configuration issue detected:");
  for (const reason of result.reasons) {
    console.log(` - ${reason}`);
  }
}

async function main() {
  const args = new Set(process.argv.slice(2));

  if (args.has("--check")) {
    const result = checkConfig();
    printCheckResult(result);
    return result.ok ? 0 : 1;
  }

  if (args.has("--set-local")) {
    setLocalPostgresEnv();
    const result = checkConfig();
    printCheckResult(result);
    return result.ok ? 0 : 1;
  }

  if (args.has("--set-docker")) {
    setDockerPostgresEnv();
    const result = checkConfig();
    printCheckResult(result);
    return result.ok ? 0 : 1;
  }

  if (args.has("--set-server")) {
    const password = process.argv[process.argv.indexOf("--set-server") + 1];
    if (password !== undefined && password.length > 0) {
      setServerPostgresEnv(password);
    } else {
      setServerPostgresEnv(process.env.PGPASSWORD || "postgres");
    }
    const result = checkConfig();
    printCheckResult(result);
    return result.ok ? 0 : 1;
  }

  if (args.has("--interactive")) {
    if (!process.stdin.isTTY) {
      console.error("[ERROR] Interactive setup requires a terminal. Run this command in cmd/powershell.");
      return 1;
    }

    try {
      await runInteractiveWizard();
    } catch (error) {
      console.error("[ERROR]", error instanceof Error ? error.message : String(error));
      return 1;
    }

    const result = checkConfig();
    printCheckResult(result);
    return result.ok ? 0 : 1;
  }

  console.log("Usage:");
  console.log("  node scripts/setup-db-env.mjs --check");
  console.log("  node scripts/setup-db-env.mjs --set-local       # local (postgres/postgres)");
  console.log("  node scripts/setup-db-env.mjs --set-docker      # Docker DB on localhost:5433");
  console.log("  node scripts/setup-db-env.mjs --set-server [pwd] # server (.env from password)");
  console.log("  node scripts/setup-db-env.mjs --interactive");
  return 0;
}

main()
  .then((code) => {
    process.exitCode = code;
  })
  .catch((error) => {
    console.error("[ERROR]", error instanceof Error ? error.message : String(error));
    process.exitCode = 1;
  });
